# Generated by Django 2.1.15 on 2020-04-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'ordering': ['user'], 'verbose_name': 'profil'},
        ),
    ]
